
from PyQt5 import QtCore, QtGui, QtWidgets
import platform,subprocess,os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 370)
        MainWindow.setStyleSheet("color: rgb(6, 176, 37);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 301, 401))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.cpuusage = QtWidgets.QProgressBar(self.tab)
        self.cpuusage.setGeometry(QtCore.QRect(20, 60, 271, 16))
        self.cpuusage.setProperty("value", 5)
        self.cpuusage.setObjectName("cpuusage")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(120, 20, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(6, 176, 37);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cpuused = QtWidgets.QLabel(self.tab)
        self.cpuused.setGeometry(QtCore.QRect(90, 100, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.cpuused.setFont(font)
        self.cpuused.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cpuused.setStyleSheet("background-color: rgb(6, 176, 37);\n"
"color: rgb(255, 255, 255);")
        self.cpuused.setTextFormat(QtCore.Qt.AutoText)
        self.cpuused.setScaledContents(False)
        self.cpuused.setAlignment(QtCore.Qt.AlignCenter)
        self.cpuused.setObjectName("cpuused")
        self.cpufree = QtWidgets.QLabel(self.tab)
        self.cpufree.setGeometry(QtCore.QRect(90, 130, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.cpufree.setFont(font)
        self.cpufree.setStyleSheet("background-color: rgb(6, 176, 37);\n"
"color: rgb(255, 255, 255);")
        self.cpufree.setAlignment(QtCore.Qt.AlignCenter)
        self.cpufree.setObjectName("cpufree")
        self.processor = QtWidgets.QLabel(self.tab)
        self.processor.setGeometry(QtCore.QRect(10, 170, 281, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.processor.setFont(font)
        self.processor.setStyleSheet("color: rgb(6, 176, 37);")
        self.processor.setAlignment(QtCore.Qt.AlignCenter)
        self.processor.setObjectName("processor")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(0, 250, 131, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(120, 240, 20, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(140, 220, 21, 81))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(130, 250, 20, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(150, 250, 20, 21))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(160, 240, 21, 41))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(170, 250, 131, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(80, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.comname = QtWidgets.QLabel(self.tab_2)
        self.comname.setGeometry(QtCore.QRect(30, 70, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.comname.setFont(font)
        self.comname.setObjectName("comname")
        self.os = QtWidgets.QLabel(self.tab_2)
        self.os.setGeometry(QtCore.QRect(30, 100, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.os.setFont(font)
        self.os.setObjectName("os")
        self.sysuptime = QtWidgets.QLabel(self.tab_2)
        self.sysuptime.setGeometry(QtCore.QRect(30, 130, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.sysuptime.setFont(font)
        self.sysuptime.setObjectName("sysuptime")
        self.sysmem = QtWidgets.QLabel(self.tab_2)
        self.sysmem.setGeometry(QtCore.QRect(30, 160, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.sysmem.setFont(font)
        self.sysmem.setObjectName("sysmem")
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(0, 250, 131, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setGeometry(QtCore.QRect(120, 240, 20, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.line_9.setFont(font)
        self.line_9.setLineWidth(1)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setGeometry(QtCore.QRect(130, 250, 20, 21))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.tab_2)
        self.line_11.setGeometry(QtCore.QRect(140, 220, 21, 81))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.tab_2)
        self.line_12.setGeometry(QtCore.QRect(170, 250, 131, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.tab_2)
        self.line_13.setGeometry(QtCore.QRect(160, 240, 21, 41))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.tab_2)
        self.line_14.setGeometry(QtCore.QRect(150, 250, 20, 21))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.warnpercent = QtWidgets.QSpinBox(self.tab_3)
        self.warnpercent.setGeometry(QtCore.QRect(200, 80, 51, 21))
        self.warnpercent.setPrefix("")
        self.warnpercent.setMinimum(1)
        self.warnpercent.setMaximum(100)
        self.warnpercent.setObjectName("warnpercent")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(40, 80, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(80, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(40, 110, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.warninterval = QtWidgets.QSpinBox(self.tab_3)
        self.warninterval.setGeometry(QtCore.QRect(200, 110, 51, 22))
        self.warninterval.setMinimum(1)
        self.warninterval.setMaximum(60)
        self.warninterval.setObjectName("warninterval")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(110, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(6, 176, 37);\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid  rgb(6, 176, 37);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.warningalert)
        self.line_15 = QtWidgets.QFrame(self.tab_3)
        self.line_15.setGeometry(QtCore.QRect(0, 250, 131, 21))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.tab_3)
        self.line_16.setGeometry(QtCore.QRect(120, 240, 20, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.line_16.setFont(font)
        self.line_16.setLineWidth(1)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.tab_3)
        self.line_17.setGeometry(QtCore.QRect(130, 250, 20, 21))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.tab_3)
        self.line_18.setGeometry(QtCore.QRect(140, 220, 21, 81))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.tab_3)
        self.line_19.setGeometry(QtCore.QRect(150, 250, 20, 21))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.tab_3)
        self.line_20.setGeometry(QtCore.QRect(160, 240, 21, 41))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(self.tab_3)
        self.line_21.setGeometry(QtCore.QRect(170, 250, 131, 20))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.changecpu)
        self.timer.start(5000)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Yashas Monitors Your CPU"))
        self.label.setText(_translate("MainWindow", "CPU"))
        self.cpuused.setText(_translate("MainWindow", "CPU Used: 5%"))
        self.cpufree.setText(_translate("MainWindow", "CPU Free: 95%"))
        self.processor.setText(_translate("MainWindow", self.cpuinfo()))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "CPU"))
        self.label_5.setText(_translate("MainWindow", "System Info"))
        sysinfo = platform.uname()
        self.comname.setText(_translate("MainWindow", f"Computer's Name : {sysinfo.node}"))
        self.os.setText(_translate("MainWindow", f"Operating System : {sysinfo.system+' '+sysinfo.release}"))
        self.sysuptime.setText(_translate("MainWindow", f"Total C.P.U. Counts : {os.cpu_count()}"))
        self.sysmem.setText(_translate("MainWindow", f"Platform's Machine : {sysinfo.machine}"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "System Info"))
        self.warnpercent.setSuffix(_translate("MainWindow", "%"))
        self.label_10.setText(_translate("MainWindow", "CPU Overload Warning :"))
        self.label_11.setText(_translate("MainWindow", "Settings"))
        self.label_12.setText(_translate("MainWindow", "Alert Frequency            :"))
        self.warninterval.setSuffix(_translate("MainWindow", "min"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Settings"))

    def getpercentage(self):
        out = subprocess.check_output(
            r'C:\Windows\System32\wbem\wmic cpu get loadpercentage')
        return int(out.decode('utf-8').split()[-1])

    def changecpu(self):
        percent = self.getpercentage()
        self.cpuusage.setValue(percent)
        self.cpuused.setText(f"CPU Used: {percent}%")
        self.cpufree.setText(f"CPU Free: {100-percent}%")
        QtCore.QCoreApplication.processEvents()

    def cpuinfo(self):
        out = subprocess.check_output(
            r'C:\Windows\System32\wbem\wmic cpu get name').decode('utf-8')
        return ' '.join(out.split()[1:])

    def warningalert(self):
        self.warningtimer = QtCore.QTimer()
        def showalert():
            if self.cpuusage.value() > self.warnpercent.value():
                ma = QtWidgets.QMessageBox()
                ma.setWindowTitle('CPU Overload!!')
                ma.setText(f'Current CPU Usage (in %) {self.cpuusage.value()}')
                ma.setIcon(QtWidgets.QMessageBox.Warning)
                ma.setStandardButtons(QtWidgets.QMessageBox.Ok)
                ma.exec_()
        showalert()
        self.warningtimer.timeout.connect(showalert)
        self.warningtimer.start(self.warninterval.value()*60000)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    
